modLoader = "kotlinforforge"
loaderVersion = "${versions.kotlin_forge}"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "arcanegardens"
version = "${modVersion}"
displayName = "Arcane Gardens"
authors = "Master_Bw3"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.arcanegardens]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arcanegardens]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arcanegardens]]
modId = "architectury"
type = "required"
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "arcanegardens-common.mixins.json"
